# See: https://github.com/github/super-linter/blob/master/TEMPLATES/.markdown-lint.yml
# See: https://github.com/github/super-linter/blob/master/docs/disabling-linters.md
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
---
MD013:        # line-length
  code_blocks: false
  tables: false
  headings: false
  line_length: 200
MD014: false  # commands-show-output
MD022:        # blanks-around-headings
  lines_above: 1
  lines_below: 0
MD024:        # no-duplicate-heading
  siblings_only: true
MD025:        # single-title/single-h1
  front_matter_title: ""
MD026:        # no-trailing-punctuation
  punctuation: ".,;:!。，；:"
MD033: false  # no-inline-html
MD044:        # proper-names
  names:
    - JavaScript
  code_blocks: false
MD046: false  # code-block-style
MD048:        # code-fence-style
  style: backtick
