# See: https://github.com/github/super-linter
---
name: Linter
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint the code base
        uses: github/super-linter@v4.8.5
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Spell check
        uses: crate-ci/typos@master
        with:
          files: docs/
